language: node_js
node_js:
  - "10"

cache: yarn

install: yarn
script:
  - yarn lint
  - yarn test:all

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "10"
      deploy:
        provider: npm
        email: "$NPM_ACCOUNT"
        api_key: "$NPM_AUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true
